# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAavhklPZg4T3iyPzw5d21BqZmpd03ge
"""

# -*- coding: utf-8 -*-
"""Assignment5
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/15Rf4qO2-3-PrCp3Os2gwW8yKaD7Gn1Vi
"""

# -*- coding: utf-8 -*-
"""Assignment-5.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1O-K9WnJtMpLfc7Nbh_L4nIHEE0a3hFRW
"""

# -*- coding: utf-8 -*-

"""Assignment-5.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1O-K9WnJtMpLfc7Nbh_L4nIHEE0a3hFRW#scrollTo=pXVvd2LjeYLY
"""
# Import our modules that we are using
import matplotlib.pyplot as plt
import numpy as np
import subprocess
import shlex
# Create the vectors X and Y
x = np.linspace(-5,5,300)
y = x ** 2  + 7*x + 10 

# Create the plot
plt.plot(x,y,label='y =x ** 2  + 7*x + 10 ')

# Add a title
plt.title('')

# Add X and y Label
plt.xlabel('x axis')
plt.ylabel('y axis')

# Add a grid
plt.grid(alpha=1,linestyle='--')

# Add a Legend
plt.legend()
plt.savefig('figure5.png')
# Show the plot
plt.show()